version: '2'
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    user: root
    depends_on:
      - db
    ports:
      - "8014:8069"
      - "20014:8072" # live chat
    tty: true
    # command: --
    command: odoo -u hrms_org
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ./hrms14:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
